
import java.util.Random;
import javax.swing.Timer;
import java.awt.event.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * arith.java
 *
 * Created on 30 Jul, 2015, 12:17:50 AM
 */

/**
 *
 * @author Mehak Jan
 */
public class arith extends javax.swing.JFrame {
   int num1, right, wrong, num2, op, sec, ans, user;
     Timer tmr;
    /** Creates new form arith */
    public arith() {
        initComponents();
        op=1;
        ri.setVisible(false);
        wr.setVisible(false);
        Random r= new Random();
        num1= r.nextInt((12 - 1 + 1))+ 0;
        l1.setText(""+ num1);
        num2= r.nextInt((12 - 1 + 1))+ 0;
        l3.setText(""+ num2);
        op= r.nextInt((3- 1 + 1))+ 1;
              switch(op)
              {
                  case 1: ans=num1+num2;
                    break;
                  case 2:ans=num1-num2;
                    break;
                  case 3: ans=num1*num2;
              }
              tf.setText(""+ ans);
        tmr= new Timer(1000, new ActionListener(){
               public void actionPerformed(ActionEvent e)
                  {
                       sec= Integer.parseInt(stopl.getText());
                       sec--;
                       if(sec==0)
                         {
                           jFrame1.setVisible(true);
                            dispose();
                            tmr.stop();
                            lr.setText(""+ right);
                            lw.setText(""+ wrong);
                            ls.setText(""+ (right*5));
                         }
               stopl.setText(""+ sec);
                 }
            }
         );
              tmr.start();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lw = new javax.swing.JTextField();
        ls = new javax.swing.JTextField();
        lr = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        stopl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ri = new javax.swing.JLabel();
        wr = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        tf = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 80));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time's Up!!");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 490, 110));

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 30));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correct");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 180, 70));

        lw.setEditable(false);
        lw.setFont(new java.awt.Font("Tahoma", 1, 24));
        lw.setForeground(new java.awt.Color(255, 255, 255));
        lw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lw.setOpaque(false);
        jPanel3.add(lw, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 50, 40));

        ls.setEditable(false);
        ls.setFont(new java.awt.Font("Tahoma", 1, 24));
        ls.setForeground(new java.awt.Color(255, 255, 255));
        ls.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ls.setOpaque(false);
        jPanel3.add(ls, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 50, 40));

        lr.setEditable(false);
        lr.setFont(new java.awt.Font("Tahoma", 1, 24));
        lr.setForeground(new java.awt.Color(255, 255, 255));
        lr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lr.setOpaque(false);
        lr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lrActionPerformed(evt);
            }
        });
        jPanel3.add(lr, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 50, 40));

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 30));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Your Score");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 290, 70));

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 30));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Incorrect");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 200, 70));

        jButton4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moving flower.gif"))); // NOI18N
        jButton4.setText("Back to Menu");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 330, 40));

        jButton5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moving flower.gif"))); // NOI18N
        jButton5.setText("Play Again");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 280, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magic.PNG"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 800, 490));

        jFrame1.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 489));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stopl.setBackground(new java.awt.Color(255, 255, 255));
        stopl.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        stopl.setText("60");
        stopl.setFocusable(false);
        jPanel1.add(stopl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 100, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animated-clock-image-0009.gif"))); // NOI18N
        jLabel4.setFocusable(false);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        ri.setFont(new java.awt.Font("AR DARLING", 1, 36));
        ri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/good2.png"))); // NOI18N
        ri.setFocusable(false);
        jPanel1.add(ri, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        wr.setFont(new java.awt.Font("AR DARLING", 1, 36));
        wr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bad7.png"))); // NOI18N
        wr.setFocusable(false);
        jPanel1.add(wr, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        l4.setFont(new java.awt.Font("Tahoma", 1, 55));
        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l4.setText("=");
        l4.setFocusable(false);
        jPanel1.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 80, 50));

        next.setFont(new java.awt.Font("AR CENA", 1, 24));
        next.setText("NEXT");
        next.setFocusable(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 100, 40));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 55));
        jLabel3.setText("Missing Operator");
        jLabel3.setFocusable(false);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 560, 70));

        jButton6.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 20));
        jButton6.setText("<<Back to Menu");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 32));
        jButton1.setText("+");
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 90, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jButton2.setText("*");
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 90, 50));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 40));
        jButton3.setText("-");
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 90, 50));

        l1.setFont(new java.awt.Font("Tahoma", 1, 40));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l1.setFocusable(false);
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 70, 50));

        l2.setFont(new java.awt.Font("Tahoma", 1, 40));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l2.setFocusable(false);
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 60, 50));

        tf.setFont(new java.awt.Font("Tahoma", 1, 40));
        tf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf.setFocusable(false);
        jPanel1.add(tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 80, 50));

        l3.setFont(new java.awt.Font("Tahoma", 1, 40));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l3.setFocusable(false);
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 70, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFocusable(false);
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 260));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eqw.PNG"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel1.setFocusable(false);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 720, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        ri.setVisible(false);
        wr.setVisible(false);
        tf.setText("");
         Random r= new Random();
        num1= r.nextInt((12 - 1 + 1))+ 0;
        l1.setText(""+ num1);
        num2= r.nextInt((12 - 1 + 1))+ 0;
        l3.setText(""+ num2);
        op= r.nextInt((3- 1 + 1))+ 1;
              switch(op)
              {
                  case 1: ans=num1+num2;
                    break;
                  case 2:ans=num1-num2;
                    break;
                  case 3: ans=num1*num2;
              }

        tf.setText(""+ ans);
        l2.setText("");
           
    }//GEN-LAST:event_nextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         user=3;
        l2.setText("*");
        if(user==op){
            ri.setVisible(true);
            right++;
        }
        else
        { wr.setVisible(true);
          wrong++;
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        user=1;
        l2.setText("+");
        if(user==op){
            ri.setVisible(true);
            right++;
        }
        else
        { wr.setVisible(true);
          wrong++;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         user=2;
        l2.setText("-");
        if(user==op){
            ri.setVisible(true);
            right++;
        }
        else
        { wr.setVisible(true);
          wrong++;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void lrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lrActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_lrActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        menu m= new menu();
        m.setVisible(true);
        jFrame1.setVisible(false);
        tmr.stop();
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        arith a =new arith();
        a.setVisible(true);
        jFrame1.setVisible(false);
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        menu m= new menu();
        m.setVisible(true);
        this.setVisible(false);
        tmr.stop();
}//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new arith().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JTextField lr;
    private javax.swing.JTextField ls;
    private javax.swing.JTextField lw;
    private javax.swing.JButton next;
    private javax.swing.JLabel ri;
    private javax.swing.JLabel stopl;
    private javax.swing.JLabel tf;
    private javax.swing.JLabel wr;
    // End of variables declaration//GEN-END:variables

}
