import java.awt.Color;
import java.util.Random;
import javax.swing.Timer;
import java.awt.event.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * color.java
 *
 * Created on 18 Dec, 2015, 8:36:22 PM
 */

/**
 *
 * @author Mehak Jan
 */
public class color extends javax.swing.JFrame {
 int color1, color2, color3;
 int user, right, wrong;
 int sec;
 Timer tmr;
    /** Creates new form color */
    public color() {
        initComponents();
      /* Random r= new Random();
        color1= r.nextInt((3 - 1 + 1))+ 1;
        color2= r.nextInt((3 - 1 + 1))+ 1;
        color3= r.nextInt((3 - 1 + 1))+ 1;
        switch(color1)
        {
            case 1: l1.setBackground(Color.RED);
                    break;
            case 2: l1.setBackground(Color.GREEN);
                    break;
              case 3: l1.setBackground(Color.BLUE);

        }
        switch(color2)
        {
            case 1: l2.setBackground(Color.RED);
                    break;
            case 2: l2.setBackground(Color.GREEN);
                    break;
              case 3: l2.setBackground(Color.BLUE);

        }
        switch(color3)
        {
            case 1: l3.setBackground(Color.RED);
                    break;
            case 2: l3.setBackground(Color.GREEN);
                    break;
              case 3: l3.setBackground(Color.BLUE);

        }*/
        ri.setVisible(false);
        wr.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ri = new javax.swing.JLabel();
        wr = new javax.swing.JLabel();
        sd = new javax.swing.JLabel();
        stopl = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l1.setOpaque(true);
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, 120));

        l2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l2.setOpaque(true);
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 110, 120));

        l3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        l3.setOpaque(true);
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 110, 120));

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setText("green");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 80, 80));

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setText("blue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 80, 80));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setText("red");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 80, 80));

        jButton4.setText("next");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 120, 50));

        ri.setFont(new java.awt.Font("AR DARLING", 1, 36));
        ri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/good2.png"))); // NOI18N
        ri.setFocusable(false);
        getContentPane().add(ri, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        wr.setFont(new java.awt.Font("AR DARLING", 1, 36));
        wr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bad7.png"))); // NOI18N
        wr.setFocusable(false);
        getContentPane().add(wr, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));
        getContentPane().add(sd, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 180, 80));

        stopl.setText("0");
        getContentPane().add(stopl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 50, 50));

        jButton5.setText("done");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 120, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       stopl.setText(""+3);
         Random r= new Random();
        color1= r.nextInt((3 - 1 + 1))+ 1;
        color2= r.nextInt((3 - 1 + 1))+ 1;
        color3= r.nextInt((3 - 1 + 1))+ 1;
        switch(color1)
        {
            case 1: l1.setBackground(Color.RED);
                    break;
            case 2: l1.setBackground(Color.GREEN);
                    break;
              case 3: l1.setBackground(Color.BLUE);

        }
        switch(color2)
        {
            case 1: l2.setBackground(Color.RED);
                    break;
            case 2: l2.setBackground(Color.GREEN);
                    break;
              case 3: l2.setBackground(Color.BLUE);
        }
        switch(color3)
        {
            case 1: l3.setBackground(Color.RED);
                    break;
            case 2: l3.setBackground(Color.GREEN);
                    break;
              case 3: l3.setBackground(Color.BLUE);
        }

     tmr= new Timer(500, new ActionListener(){
               public void actionPerformed(ActionEvent e)
                  {
                       sec= Integer.parseInt(stopl.getText());
                       sec--;
                       if(sec==0)
                         {
                            l1.setBackground(Color.WHITE);
                             l2.setBackground(Color.WHITE);
                             l3.setBackground(Color.WHITE);
                               tmr.stop();
                         }
               stopl.setText(""+ sec);
                 }
            }
         );
              tmr.start();
              ri.setVisible(false);
              wr.setVisible(false);
        //for(int i=1; i<1000000000; i++)
        
        {
            
        }
       /// for(int j=1; j<1000000000; j++)
            {
            }
        //l1.setBackground(Color.WHITE);
       // l2.setBackground(Color.WHITE);
       // l3.setBackground(Color.WHITE);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        user=1;
        if(user==color1)
          right++;
        else
            wrong++;
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        user=2;
        if(user==color2)
          right++;
        else
            wrong++;
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        user=3;
        if(user==color3)
           right++;
        else
            wrong++;

        
        
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(right==3)
            ri.setVisible(true);
        else
            wr.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new color().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel ri;
    private javax.swing.JLabel sd;
    private javax.swing.JLabel stopl;
    private javax.swing.JLabel wr;
    // End of variables declaration//GEN-END:variables

}
