import java.util.Random;
import javax.swing.Timer;
import java.awt.event.*;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fishpedia.java
 *
 * Created on 17 Jul, 2015, 12:57:42 PM
 */

/**
 *
 * @author Mehak Jan
 */
public class fishpedia extends javax.swing.JFrame {
     int right, wrong, flag=0;
     int ran;
     int sec;
     Timer tmr;
    /** Creates new form fishpedia */
    public fishpedia() {
        initComponents();
        ran=1;
        next.setVisible(false);
        ri.setVisible(false);
        wr.setVisible(false);
       tmr= new Timer(1000, new ActionListener(){
               public void actionPerformed(ActionEvent e)
                  {
                       sec= Integer.parseInt(stopl.getText());
                       sec--;
                       if(sec==0)
                         {
                            jFrame1.setVisible(true);
                            dispose();
                            tmr.stop();
                            lr.setText(""+ right);
                            lw.setText(""+ wrong);
                            ls.setText(""+ (right*5));
                         }
               stopl.setText(""+ sec);
                 }
            }
         );
              tmr.start();
     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lw = new javax.swing.JTextField();
        ls = new javax.swing.JTextField();
        lr = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ri = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        wr = new javax.swing.JLabel();
        ques = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        stopl = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        done = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tf = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jFrame1.setAlwaysOnTop(true);
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 80)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time's Up!!");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 490, 110));

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correct");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 180, 70));

        lw.setEditable(false);
        lw.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lw.setForeground(new java.awt.Color(255, 255, 255));
        lw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lw.setOpaque(false);
        lw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lwActionPerformed(evt);
            }
        });
        jPanel3.add(lw, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 50, 40));

        ls.setEditable(false);
        ls.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ls.setForeground(new java.awt.Color(255, 255, 255));
        ls.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ls.setOpaque(false);
        jPanel3.add(ls, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 50, 40));

        lr.setEditable(false);
        lr.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lr.setForeground(new java.awt.Color(255, 255, 255));
        lr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lr.setOpaque(false);
        lr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lrActionPerformed(evt);
            }
        });
        jPanel3.add(lr, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 50, 40));

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Your Score");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 290, 70));

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Incorrect");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 200, 70));

        jButton2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moving flower.gif"))); // NOI18N
        jButton2.setText("Back to Menu");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 330, 40));

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moving flower.gif"))); // NOI18N
        jButton1.setText("Play Again");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 280, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magic.PNG"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 480));

        jFrame1.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 807, 489));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(776, 515));
        getContentPane().setLayout(null);

        ri.setFont(new java.awt.Font("AR DARLING", 1, 36)); // NOI18N
        ri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/good2.png"))); // NOI18N
        ri.setFocusable(false);
        getContentPane().add(ri);
        ri.setBounds(280, 180, 60, 80);

        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AquaRegia");
        jLabel2.setFocusable(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 20, 260, 60);

        wr.setFont(new java.awt.Font("AR DARLING", 1, 36)); // NOI18N
        wr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bad7.png"))); // NOI18N
        wr.setFocusable(false);
        getContentPane().add(wr);
        wr.setBounds(280, 180, 60, 80);

        ques.setFont(new java.awt.Font("AR CENA", 1, 42)); // NOI18N
        ques.setForeground(new java.awt.Color(51, 0, 0));
        ques.setText("Number of Pearls?");
        ques.setFocusable(false);
        getContentPane().add(ques);
        ques.setBounds(170, 320, 420, 70);

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.PNG"))); // NOI18N
        l1.setFocusable(false);
        getContentPane().add(l1);
        l1.setBounds(30, 100, 550, 220);

        stopl.setBackground(new java.awt.Color(255, 255, 255));
        stopl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        stopl.setForeground(new java.awt.Color(255, 255, 255));
        stopl.setText("60");
        stopl.setFocusable(false);
        getContentPane().add(stopl);
        stopl.setBounds(650, 50, 50, 50);

        next.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        next.setText("NEXT");
        next.setFocusable(false);
        next.setNextFocusableComponent(tf);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next);
        next.setBounds(600, 250, 100, 40);

        done.setFont(new java.awt.Font("AR CENA", 1, 24)); // NOI18N
        done.setText("DONE");
        done.setFocusable(false);
        done.setNextFocusableComponent(tf);
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        getContentPane().add(done);
        done.setBounds(600, 190, 100, 40);

        jButton3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 18)); // NOI18N
        jButton3.setText("<<Back to Menu");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(-20, 450, 240, 29);

        tf.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(tf);
        tf.setBounds(300, 380, 70, 60);

        jPanel1.setFocusable(false);
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animated-fish-image-0019.gif"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 90, 90));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 10, 170, 90);

        jPanel2.setFocusable(false);
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animated-fish-image-0023.gif"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 30, 130, 150);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(500, 300, 210, 180);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/animated-clock-image-0009.gif"))); // NOI18N
        jLabel4.setFocusable(false);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(590, 30, 70, 80);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sswsw.PNG"))); // NOI18N
        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 479);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        // TODO add your handling code here:
         
        int user= Integer.parseInt(tf.getText());
       
        switch(ran)
        {
            case 1: if(user==11)
                        right++;
                    else
                        wrong++;
                    break;
            case 2: if(user==3)
                        right++;
                    else
                        wrong++;
                    break;
            case 3: if(user==7)
                        right++;
                    else
                        wrong++;
                    break;
            case 4: if(user==3)
                        right++;
                    else
                        wrong++;
                    break;
            case 5: if(user==7)
                        right++;
                    else
                        wrong++;
                    break;
            case 6:  if(user==10)
                        right++;
                    else
                        wrong++;
                    break;
            case 7: if(user==10)
                       right++;
                    else
                        wrong++;
                    break;
            case 8: if(user==5)
                       right++;
                    else
                        wrong++;
                    break;
            case 9: if(user==11)
                       right++;
                    else
                        wrong++;
                    break;
            case 10: if(user==10)
                       right++;
                    else
                        wrong++;
                     break;
            case 11: if(user==10)
                     right++;
                    else
                        wrong++;
                     break;
        }
        done.setVisible(false);
        next.setVisible(true);
        if(right>flag)
        {
          ri.setVisible(true);
          flag++;
        }
        else
            wr.setVisible(true);
           
          
        
         
}//GEN-LAST:event_doneActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
       done.setVisible(true);
        ri.setVisible(false);
        wr.setVisible(false);
        tf.setText("");
        Random r= new Random();
        ran= r.nextInt((11 - 1 + 1))+ 1;
        switch(ran)
        {
            case 1:l1.setIcon(new ImageIcon("src\\1.PNG"));
                l1.setVisible(true);
                  ques.setText("Number of Pearls?");
                  break;
             case 2:l1.setIcon(new ImageIcon("src\\2.PNG"));
                  ques.setText("Number of Crabs?");
                  break;
             case 3:l1.setIcon(new ImageIcon("src\\3.PNG"));
                   ques.setText("Number of Pearls?");
                  break;
             case 4:l1.setIcon(new ImageIcon("src\\4.PNG"));
                    ques.setText("Number of Star fishes?");
                  break;
             case 5:l1.setIcon(new ImageIcon("src\\5.PNG"));
                    ques.setText("Number of Crabs?");
                  break;
             case 6:l1.setIcon(new ImageIcon("src\\6.PNG"));
                     ques.setText("Number of Pearls?");
                  break;
             case 7:l1.setIcon(new ImageIcon("src\\7.PNG"));
                     ques.setText("Number of Star fishes?");
                  break;
             case 8:l1.setIcon(new ImageIcon("src\\8.PNG"));
                      ques.setText("Number of Crabs?");
                  break;
              case 9:l1.setIcon(new ImageIcon("src\\9.PNG"));
                     ques.setText("Number of Pearls?");
                  break;
              case 10:l1.setIcon(new ImageIcon("src\\10.PNG"));
                       ques.setText("Number of Star fishes?");
                  break;
              case 11:l1.setIcon(new ImageIcon("src\\11.PNG"));
                         ques.setText("Number of Crabs?");
                  break;

        }
        next.setVisible(false);

       

}//GEN-LAST:event_nextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        menu m= new menu();
        m.setVisible(true);
        this.setVisible(false);
        tmr.stop();
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        menu me= new menu();
        me.setVisible(true);
        jFrame1.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lrActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_lrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fishpedia f= new fishpedia();
        f.setVisible(true);
       jFrame1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lwActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fishpedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton done;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel l1;
    private javax.swing.JTextField lr;
    private javax.swing.JTextField ls;
    private javax.swing.JTextField lw;
    private javax.swing.JButton next;
    private javax.swing.JLabel ques;
    private javax.swing.JLabel ri;
    private javax.swing.JLabel stopl;
    private javax.swing.JTextField tf;
    private javax.swing.JLabel wr;
    // End of variables declaration//GEN-END:variables

}
